name: Container 

on:
  workflow_call:
    inputs:
      name:
        type: string
        default: ${{ github.event.repository.name }}

      container-file:
        type: string
        default: Dockerfile

      cache-from:
        type: string
        default: type=gha

      timeout-minutes:
        type: number
        default: 15

      push-to-registry:
        type: boolean
        default: true

      google-project-id:
        type: string
        default: ${{ vars.GOOGLE_PROJECT_ID }}
      
      workload-identity-provider:
        type: string
        default: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}

      artifact-service-account-email:
        type: string
        default: ${{ vars.ARTIFACT_SERVICE_ACCOUNT_EMAIL }}

      container-registry:
        type: string
        default: ${{ vars.CONTAINER_REGISTRY }}

    outputs:
      tag:
        description: "The output of the tag"
        value: ${{ jobs.build-container.outputs.tag }}
      image:
        description: "The image name"
        value: ${{ jobs.build-container.outputs.image }}

jobs:
  build-container:
      name: Build and Publish

      runs-on: ubuntu-latest
      timeout-minutes: ${{ inputs.timeout-minutes }}
      
      permissions:
        contents: read
        packages: write
        id-token: write

      env:
        IMAGE_NAME: ${{ inputs.container-registry }}/${{ inputs.name }}
        IS_DEFAULT_BRANCH: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}

      outputs:
        tag: ${{ steps.meta-ghcr.outputs.version }}
        image: ${{ env.IMAGE_NAME }}

      steps:
        - name: Validate environment
          if: ${{ inputs.push-to-registry == true }}
          shell: bash
          run: |
            if [ -z "${{ inputs.google-project-id }}" ]; then
              echo "Missing GOOGLE_PROJECT_ID secret"
              exit 1
            fi
            if [ -z "${{ inputs.workload-identity-provider }}" ]; then
              echo "Missing WORKLOAD_IDENTITY_PROVIDER secret"
              exit 1
            fi
            if [ -z "${{ inputs.artifact-service-account-email }}" ]; then
              echo "Missing ARTIFACT_SERVICE_ACCOUNT_EMAIL secret"
              exit 1
            fi

        - name: Checkout 🛎️
          uses: actions/checkout@v4

        - name: Authenticate with Google 🔑
          if: ${{ inputs.push-to-registry == true }}
          id: auth
          uses: google-github-actions/auth@v2
          with:
            token_format: access_token
            project_id: ${{ inputs.google-project-id }}
            workload_identity_provider: ${{ inputs.workload-identity-provider }}
            service_account: ${{ inputs.artifact-service-account-email }}

        - name: Authenticate with Docker 🔑
          if: ${{ inputs.push-to-registry == true }}
          uses: docker/login-action@v3
          with:
            registry: europe-north1-docker.pkg.dev
            username: oauth2accesstoken
            password: ${{ steps.auth.outputs.access_token }}

        - name: Docker meta 🏷
          id: meta-ghcr
          uses: docker/metadata-action@v5
          with:
            images: ${{ env.IMAGE_NAME }}
            tags: |
              type=raw,value=latest,enable=${{ env.IS_DEFAULT_BRANCH }}
              type=sha,suffix=-{{branch}},priority=1001
              type=ref,event=pr

        - name: Set up Docker Buildx 🔨
          id: buildx
          uses: docker/setup-buildx-action@v3

        - name: Build and Push Container 🛠
          id: build-and-push
          uses: docker/build-push-action@c382f710d39a5bb4e430307530a720f50c2d3318 # v6
          with:
            context: ./
            file: ${{ inputs.container-file }}
            push: ${{ inputs.push-to-registry }} 
            tags: |
              ${{ steps.meta-ghcr.outputs.tags }}
              ${{ steps.meta-gar.outputs.tags }}
            labels: ${{ steps.meta-ghcr.outputs.labels }}
            cache-from: ${{ inputs.cache-from }}
            cache-to: type=gha,mode=max