name: PNPM Typical

on:
  workflow_call:
    inputs:
      use-engines:
        type: boolean
        description: 'Use Node version from package.json'
        required: false
        default: false
      node-version:
        type: string
        description: 'Node version. Defaults to active LTS.'
        required: false
        default: lts/*
      timeout-minutes:
        type: number
        description: 'Timeout in minutes for the workflow run. Defaults to 30.'
        required: false
        default: 30

jobs:
  build:
    name: Lint, format, test and build
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout-minutes }}

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Setup pnpm 📦️
        uses: pnpm/action-setup@v2

      - name: Find Node version to use 🧐
        run: |
          USE_ENGINES=${{ inputs.use-engines }}
          if [ $USE_ENGINES == 'true' ]; then
            echo "Using Node version from package.json"
            echo "version=$(node -p "require('./package.json').engines.node")" >> $GITHUB_OUTPUT
          else
            echo "version=${{ inputs.node-version }}" >> $GITHUB_OUTPUT
          fi
        id: find-node-version

      - name: Setup Node ✨
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: ${{ steps.find-node-version.outputs.version }}
          cache: pnpm

      - name: Install dependencies 📦️
        run: pnpm install --frozen-lockfile

      - name: Build 🔨
        run: pnpm run --if-present build

      - name: Lint 🔍
        run: pnpm run --if-present lint

      - name: Format 🖌️
        run: pnpm run --if-present format

      - name: Test 🧪
        run: pnpm run --if-present test
