name: Test Action

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  typical-pnpm-workflow:
    name: Test
    uses: ./.github/workflows/pnpm-typical.yml
  typical-bun-workflow:
    name: Test
    uses: ./.github/workflows/bun-typical.yml
  typical-pnpm-workflow-use-engine:
    name: Test with use-engine
    uses: ./.github/workflows/pnpm-typical.yml
    with:
      use-engines: true
